### ISSUE TITLE
Split fails when there is more than one equals sign

### ISSUE THREAD

**Issue by xsacha** [vmware/open-vmdk#33]
### Describe the bug

If you have a config value that contains an equals sign, you will arrive at this error:

> Traceback (most recent call last):
>   File "/tmp/open-vmdk/bin/ova-compose", line 1187, in <module>
>     main()
>   File "/tmp/open-vmdk/bin/ova-compose", line 1099, in main
>     k,v = a.split('=')
> ValueError: too many values to unpack (expected 2)

My fix here:
https://github.com/xsacha/open-vmdk/commit/2574cd7d99364331fb449ee8917ba82d17502116

### Reproduction steps

```
environment:
    properties:
        guestinfo.ignition.config.data:
            value: blah=
            user_configurable: true
            type: string
            description: "Ignition Data"
            label: "Ignition"
```

### Expected behavior

Works
