### ISSUE TITLE
Allow adding a Category to a ProductSection

### ISSUE THREAD

**Issue by xsacha** [vmware/open-vmdk#35]
### Is your feature request related to a problem? Please describe.

Currently all the OVF Properties are added as 'uncategorized' which is ugly and causes UI bloat at customisation time.

### Describe the solution you'd like

The ability to put a category on an OVFProduct.

### Describe alternatives you've considered

```XML
<ProductSection>
  <Info>Test</Info>
  <Product>Test Product</Product>
  <Vendor>Test Vendor</Vendor>
  <Version>1.0.0</Version>
  <FullVersion>Test</FullVersion>
  <Category>Hardware</Category> <!-- INJECT THIS -->
  <Property ovf:key="blah" ovf:type="int" ovf:value="2" ovf:userConfigurable="true">
    <Label>GPUs to use</Label>
    <Description>How many GPUs to use</Description>
  </Property>
</ProductSection>
```

**Comment by oliverkurth** [comment]
Thanks for reporting. This makes sense, I will add this as soon as I find the time.

I was thinking about implementing it like this, by adding the `categories` to `environment`, and then they get referenced from the `properties`:
```
environment:
...
    categories:
        email:
            name: "Email Stuff"
        login:
            name: "Login Details"
    properties:
        guestinfo.admin.email:
            value: admin@company.org
            user_configurable: true
            type: string
            description: "The Admin's email address"
            label: "Email Address"
            category: email
        guestinfo.password:
            password: true
            user_configurable: true
            type: string
            description: "The Admin's Password"
            label: "Password"
            category: login
```
